### ISSUE TITLE
Unable to run either `tag` or `test` operation

### ISSUE THREAD

**Issue by frankliu2023** [yanshao9798/tagger#1]
Hi Yan Shao,

Thanks so much for the paper and this implementation. Great work! 

I was trying to run some tests. However, I couldn't run either `tag` or `test` operation after finish training following your instruction in readme file. I'm wondering if you could help me.

This is the command I used to train model:
`python tagger.py train -p ud1 -t train.txt -d dev.txt -wv -cp -rd -gru -m model_ud1 -emb Embeddings/glove.txt`

After training, I do get couple files generated under `ud1` directory, including:
`model_ud1_model`, `model_ud1_weights.data-00000-of-00001`, `model_ud1_weights.index`, and some other files.

However, when I run the following command
`python tagger.py tag -p ud1 -wv -cp -rd -gru -m model_ud1 -emb Embeddings/glove.txt`

I get some errors like this:

```
Encoding:  utf-8
Traceback (most recent call last):
  File "tagger.py", line 226, in <module>
    raise Exception('No model file or weights file under the name of ' + model_file + '.')
Exception: No model file or weights file under the name of model_ud1.
```

I also tried to rename file `model_ud1_weights.data-00000-of-00001` to `model_ud1_weights`, but get some segmentation fail error.

Looking forward to your response. Thanks a lot!

**Comment by yanshao9798** [comment]
Hi! I forgot to change a few places when I updated the code from old TensorFlow to TensorFlow 1.2.0. It should be fine now. Thanks for pointing out the problem. Let me know if you have further questions.
