### ISSUE TITLE
Can I add a custom dictionary with POS to segment and tag?

### ISSUE THREAD

**Issue by GabrielLin** [yanshao9798/tagger#12]
If it can, how? Thanks.

**Comment by yanshao9798** [comment]
I think it is very difficult to directly integrate a dictionary in the model, but you can use your dictionary for post-processing.

**Comment by GabrielLin** [comment]
Yep, post-processing is a good idea. But I want to use that dictionary also for segment. It seems that I can just generate some corpus of words in the dictionary and retrain the model.
