### ISSUE TITLE
Code about Character Representations?

### ISSUE THREAD

**Issue by GabrielLin** [yanshao9798/tagger#13]
Could you please share the about Character Representations in the paper 2.3? The way to construct glove.txt. Thanks.

**Comment by yanshao9798** [comment]
glove.txt is just trained via the regular GloVe code (https://nlp.stanford.edu/projects/glove/) using the freely available corpora that I mentioned in the paper.

**Comment by GabrielLin** [comment]
What about the 2.3.2 Radicals and Orthographical Features? Does it extract online?

**Comment by yanshao9798** [comment]
Yes. Use -rd for radical features and -pt for orthographical features.

**Comment by GabrielLin** [comment]
Why not to train and combine these features and the vector trained by GloVe into a file? Maybe there can be three files. One for GloVe vector, one for GloVe + radical features and one for GloVe + orthographical features. In my opinion, it will be faster than online extraction.

**Comment by yanshao9798** [comment]
You are absolutely right about the orhographical features. Since it doesn't really help the performance so much, I didn't implement it in the code. But in theory that's the more efficient way to go.

**Comment by GabrielLin** [comment]
Got it. Thanks.
