### ISSUE TITLE
glove.txt issue

### ISSUE THREAD

**Issue by programmer9208** [yanshao9798/tagger#16]
Hello, guys:
Why does the Embedding/glove.txt has dumplicated word vector? 
For example:
伊 0.058098 0.022144 -0.117942 0.593324 0.356539 -0.281961 0.286887 -0.044168 0.748840 0.929442 0.278035 0.365051 0.323523 -0.806431 0.080220 0.230459 -0.399853 -0.905527 0.357535 -0.015244 -0.447136 0.888065 0.458614 0.687096 -0.235226 0.514639 0.601631 -0.833810 0.131076 0.453951 1.626491 0.001660 0.342886 0.313260 -0.337498 0.470956 0.461126 -0.215516 -1.035359 0.379762 -0.978667 0.045194 0.679405 -0.119277 -0.039759 -0.074029 0.612631 -0.464666 0.230290 -0.920909 0.187592 -0.305234 0.791345 -0.478757 -1.044150 0.102264 -0.033122 -0.461046 0.215913 -0.317818 -0.036012 -0.988583 0.352062 0.644296
伊 -0.364829 0.147071 -0.201205 -0.005680 -0.448284 -0.185119 -0.240706 0.092233 -0.054130 -0.191811 0.653854 -0.180990 -0.271582 0.086690 -0.086819 0.280297 -0.065135 -0.070904 0.150856 -0.640819 -0.237637 0.062954 -0.132440 0.508728 0.174249 0.090682 0.592998 0.127657 0.524285 -0.084168 0.413616 0.213899 0.227537 -0.004896 -0.192775 0.057657 -0.131379 0.260663 -0.439500 -0.087078 -0.213280 -0.471044 0.274838 0.033694 -0.212054 -0.779220 0.121394 0.289912 -0.431739 0.611416 -0.072045 0.286813 -0.472429 -0.316691 -0.732993 -0.088714 0.070770 0.398171 0.208513 0.250378 -0.621431 -0.107010 -0.502995 -0.601222

I also find a '======' line in the file. Is it a git merge error?

**Comment by yanshao9798** [comment]
Hi! It should be fixed now. Please inform me if you encounter further questions. Thanks!
