### ISSUE TITLE
How to segment raw text without POS tagging?

### ISSUE THREAD

**Issue by reid3290** [yanshao9798/tagger#17]
Hi, Yan Shao. I am wondering how to use your code to do word segmentation only without outputting POS tags. By the way, according to your doc, when tagging raw text,  `-p` is required. What is it meant for? 
Thx.

**Comment by yanshao9798** [comment]
Hi! There are two ways:

1. Just write a post editing script to remove the POS tags if you don't want them.
2. Retrain the model by adding the parameter `-tg seg`. In this way, the model only does segmentation and therefore will be faster both for training and tagging, but will be less accurate as it cannot benefit from the POS tags.  

The `-p` parameter points to the directory where the weights of your model is stored.

Hope it helps!
