### ISSUE TITLE
A typo of README

### ISSUE THREAD

**Issue by reid3290** [yanshao9798/tagger#2]
```python tagger.py test -p ud1 -e test.txt -m model1_ud1 -emb Embeddings/glove.txt```
should be ```python tagger.py test -p ud1 -e test.txt -m model_ud1 -emb Embeddings/glove.txt```.
model1 _ud1 => model_ud1, otherwise the code complains ```Exception: No model file or weights file under the name of model1_ud1```

**Comment by yanshao9798** [comment]
Thanks! Now it is fixed. :)
