### ISSUE TITLE
Training process killed

### ISSUE THREAD

**Issue by reid3290** [yanshao9798/tagger#3]
Hi, @yanshao9798 
I trained the model using ud1 corpus and it's all right. But when I trained it using CTB corpus, the training process was killed by kernel without any warning. After several searches, I thinks it's because of out of memory problem. My machine only has 16G memory. I want to increase it, but how much memory do i need? What your experience?
Thanks.

**Comment by yanshao9798** [comment]
Hi Reid,
If you have less memory, you can set a larger bucket size (30, 40 or 50) by -bt, which slows down the training speed but does not lead to performance loss. Hope it helps!
Best,
Yan

**Comment by reid3290** [comment]
Hi Yan, setting a larger bucket size does work, thanks for you help.
