### ISSUE TITLE
unsupported operand type(s) for -: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by GabrielLin** [yanshao9798/tagger#8]
When I run:
`python tagger.py test -p ud1 -e test.txt -m model_ud1 -emb Embeddings/glove.txt`

The test run result has successfully be shown. But last line shows an error:

> Traceback (most recent call last):
>   File "tagger.py", line 558, in <module>
>     print('Done. Time consumed: %d seconds' % int(time() - s_time))
> TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
> 

I am afraid that you have not init s_time when args.action is 'test'.

**Comment by yanshao9798** [comment]
It is now fixed. Thanks for pointing it out.
